name: Keep Render App Awake

on:
  schedule:
    - cron: "*/5 * * * *" # cada 5 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /health
        run: |
          curl -s https://spring-boot-email.onrender.com/health
